// <auto-generated />
using System;
using Ecommerce_Product_API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecommerce_Product_API.Migrations
{
    [DbContext(typeof(HarvestContext))]
    partial class HarvestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce_Product_API.Models.AttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer")
                        .HasColumnName("attribute_id");

                    b.Property<string>("AttributeValue1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attribute_value");

                    b.HasKey("Id")
                        .HasName("attribute_values_pkey");

                    b.HasIndex("AttributeId");

                    b.ToTable("attribute_values", (string)null);
                });

            modelBuilder.Entity("Ecommerce_Product_API.Models.Attribute_", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("attributes_pkey");

                    b.ToTable("attributes", (string)null);
                });

            modelBuilder.Entity("Ecommerce_Product_API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ProductId"));

                    b.Property<string>("BrandProduct")
                        .HasColumnType("text")
                        .HasColumnName("brand_product");

                    b.Property<string>("CategoryProduct")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_product");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LongDescriptionProduct")
                        .HasColumnType("text")
                        .HasColumnName("long_descriptionProduct");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("ProductId")
                        .HasName("product_pkey");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Ecommerce_Product_API.Models.ProductVariant", b =>
                {
                    b.Property<int>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("variant_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("VariantId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("base_price");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("sale_price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("VariantId")
                        .HasName("variant_pkey");

                    b.HasIndex("ProductId");

                    b.ToTable("product_variants", (string)null);
                });

            modelBuilder.Entity("Ecommerce_Product_API.Models.VariantAttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeValueId")
                        .HasColumnType("integer")
                        .HasColumnName("attribute_value_id");

                    b.Property<int>("VariantId")
                        .HasColumnType("integer")
                        .HasColumnName("variant_id");

                    b.HasKey("Id")
                        .HasName("variant_attribute_values_pkey");

                    b.HasIndex("VariantId");

                    b.ToTable("variant_attribute_values", (string)null);
                });

            modelBuilder.Entity("Ecommerce_Product_API.Models.AttributeValue", b =>
                {
                    b.HasOne("Ecommerce_Product_API.Models.Attribute_", "Attribute")
                        .WithMany("AttributeValues")
                        .HasForeignKey("AttributeId")
                        .IsRequired()
                        .HasConstraintName("attribute_id_fkey");

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("Ecommerce_Product_API.Models.ProductVariant", b =>
                {
                    b.HasOne("Ecommerce_Product_API.Models.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("product_fkey");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce_Product_API.Models.VariantAttributeValue", b =>
                {
                    b.HasOne("Ecommerce_Product_API.Models.ProductVariant", "Variant")
                        .WithMany("VariantAttributeValues")
                        .HasForeignKey("VariantId")
                        .IsRequired()
                        .HasConstraintName("variant_fkey");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Ecommerce_Product_API.Models.Attribute_", b =>
                {
                    b.Navigation("AttributeValues");
                });

            modelBuilder.Entity("Ecommerce_Product_API.Models.Product", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("Ecommerce_Product_API.Models.ProductVariant", b =>
                {
                    b.Navigation("VariantAttributeValues");
                });
#pragma warning restore 612, 618
        }
    }
}
